# Generated by Django 6.0 on 2025-12-10 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('model_file', models.CharField(max_length=500)),
                ('preprocessor_file', models.CharField(blank=True, max_length=500, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('training_mode', models.CharField(choices=[('new', 'New Training'), ('fine_tune', 'Fine Tuning')], default='new', max_length=20)),
                ('model_type', models.CharField(max_length=100)),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='model_registry.modelartifact')),
            ],
            options={
                'verbose_name': 'Model Artifact',
                'verbose_name_plural': 'Model Artifacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
