# Generated by Django 6.0 on 2025-12-10 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDataHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=200)),
                ('dataset_hash', models.CharField(max_length=64)),
                ('row_count', models.IntegerField(default=0)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_history', to='model_registry.modelartifact')),
            ],
            options={
                'verbose_name': 'Training Data History',
                'verbose_name_plural': 'Training Data Histories',
                'ordering': ['-trained_at'],
                'indexes': [models.Index(fields=['model_version', 'dataset_hash'], name='model_regis_model_v_ec8b4b_idx')],
            },
        ),
    ]
