# Generated by Django 6.0 on 2025-12-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=50)),
                ('input_data', models.JSONField(default=dict)),
                ('prediction', models.JSONField(default=dict)),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inference Log',
                'verbose_name_plural': 'Inference Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
